PROJECT_ID := 
PROJECT_NUMBER := 
ACCOUNT := 
ACCOUNT_ID :=
SERVICE_ACCOUNT :=
REGION :=

APP := radioactivity-map
RADIOACTIVITY_API_URL := https://api-radioactivity-123456.web.app
FIREBASE_APIKEY :=
FIREBASE_AUTHDOMAIN :=
FIREBASE_PROJECTID :=
FIREBASE_STORAGEBUCKET :=
FIREBASE_MESSAGINGSENDERID :=
FIREBASE_APPID :=
FIREBASE_MEASUREMENTID :=

init:
	gcloud services enable cloudbilling.googleapis.com --project=$(PROJECT_ID)
	gcloud beta billing projects link $(PROJECT_ID) --billing-account=$(ACCOUNT_ID)
	gcloud services enable cloudbuild.googleapis.com --project=$(PROJECT_ID)
	gcloud services enable run.googleapis.com --project=$(PROJECT_ID)

deploy:
	NODE_ENV=production \
		GENERATE_SOURCEMAP=false \
		REACT_APP_ROUTE_BASENAME='' \
		REACT_APP_RADIOACTIVITY_API_URL=$(RADIOACTIVITY_API_URL) \
		REACT_APP_FIREBASE_APIKEY=$(FIREBASE_APIKEY) \
		REACT_APP_FIREBASE_AUTHDOMAIN=$(FIREBASE_AUTHDOMAIN) \
		REACT_APP_FIREBASE_PROJECTID=$(FIREBASE_PROJECTID) \
		REACT_APP_FIREBASE_STORAGEBUCKET=$(FIREBASE_STORAGEBUCKET) \
		REACT_APP_FIREBASE_MESSAGINGSENDERID=$(FIREBASE_MESSAGINGSENDERID) \
		REACT_APP_FIREBASE_APPID=$(FIREBASE_APPID) \
		REACT_APP_FIREBASE_MEASUREMENTID=$(FIREBASE_MEASUREMENTID) \
		yarn react-scripts build

	firebase deploy --only hosting --project radioactivity-123456
